# Generated by Django 3.2.6 on 2021-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210825_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gas',
            field=models.ManyToManyField(to='main_app.Gas'),
        ),
    ]
